INSERT INTO
    `booking_movings` (
        `id`,
        `booking_id`,
        `transaction_id`,
        `payment_method`,
        `service_price`,
        `distance_price`,
        `floor_assess_price`,
        `floor_plan_price`,
        `job_details_price`,
        `no_of_room_price`,
        `priority_price`,
        `weight_price`,
        `sub_total`,
        `tax_price`,
        `helper_fee`,
        `total_price`,
        `payment_status`,
        `payment_at`,
        `accepted_at`,
        `start_booking_image`,
        `signatureStart`,
        `start_booking_at`,
        `start_intransit_at`,
        `complete_booking_image`,
        `signatureCompleted`,
        `complete_booking_at`,
        `incomplete_reason`,
        `incomplete_booking_at`,
        `created_at`,
        `updated_at`
    )
VALUES (
        1,
        46,
        NULL,
        'cod',
        '40.00',
        '766.73',
        '20.00',
        '0.00',
        '960.00',
        '0.00',
        '2.00',
        '0.00',
        '1788.73',
        '196.76',
        '0.00',
        '1985.49',
        'paid',
        '2024-08-23 17:37:41',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '2024-08-23 17:37:30',
        '2024-08-23 17:37:41'
    );